import test from 'node:test';import assert from 'node:assert/strict';
import {localTime,monday,runInput,defaultData,rulesFor,parsePlan,nvidia,context} from '../lib/domain.mjs';
test('local calendar survives midnight, DST and year boundaries',()=>{assert.equal(localTime('Europe/Prague',new Date('2026-09-06T23:30:00Z')).date,'2026-09-07');assert.equal(localTime('America/Los_Angeles',new Date('2026-01-01T01:00:00Z')).date,'2025-12-31');assert.equal(monday('2026-03-29'),'2026-03-23');assert.throws(()=>localTime('invalid'));});
test('runs reject impossible/future dates and preserve actual effort',()=>{assert.throws(()=>runInput({date:'2026-02-30',distance:5,movingSeconds:1500},'2026-09-06'));assert.throws(()=>runInput({date:'2026-09-07',distance:5,movingSeconds:1500},'2026-09-06'));const r=runInput({date:'2026-09-06',distance:5,time:'30:00'},'2026-09-06');assert.equal(r.movingSeconds,1800);assert.equal(r.effort,null);});
test('plan validation caps load, locks completed days and refuses excess intensity',()=>{const d=defaultData();d.profile.days=[0,2,4];d.runs=[{date:'2026-09-06',distance:5,movingSeconds:1800,effort:9}];const now=new Date('2026-09-07T10:00:00Z');const rules=rulesFor(d,now);assert.equal(rules.maxHardSessions,0);assert.equal(rules.remainingKm,5);assert.equal(context(d,now).stats.averagePaceSecondsPerKm,360);const p={explanation:'Podle posledního běhu.',days:Array.from({length:7},(_,day)=>({day,type:'Volno',distanceKm:0,paceFast:null,paceSlow:null,description:'Odpočinek'}))};assert.equal(parsePlan(JSON.stringify(p),d,now).week,'2026-09-07');p.days[0]={day:0,type:'Lehký běh',distanceKm:6,paceFast:390,paceSlow:430,description:'Lehce'};assert.throws(()=>parsePlan(JSON.stringify(p),d,now));});
test('NVIDIA requests use fixed provider and reject incomplete/error replies',async()=>{let sent;const mock=async(url,opts)=>{sent={url,...JSON.parse(opts.body)};return Response.json({choices:[{finish_reason:'stop',message:{content:'OK'}}]});};assert.equal(await nvidia('test',[{role:'user',content:'Ahoj'}],false,mock),'OK');assert.equal(sent.chat_template_kwargs.enable_thinking,false);assert.equal(sent.url,'https://integrate.api.nvidia.com/v1/chat/completions');await assert.rejects(nvidia('test',[],false,async()=>new Response('',{status:429})),/limit/);await assert.rejects(nvidia('test',[],false,async()=>Response.json({choices:[{finish_reason:'length',message:{content:'partial'}}]})),/úplná/);});

import {mergeDesktop} from '../lib/domain.mjs';
test('desktop merge carries independent changes both ways and propagates deletions',()=>{const data=defaultData(),a=runInput({id:'a',date:'2026-09-01',distance:5,movingSeconds:1800},'2026-09-06'),b={...a,id:'b'},c={...a,id:'c'};data.runs=[a,b];const baseline={runs:[a],profile:data.profile};const merged=mergeDesktop(data,{runs:[a,c],profile:data.profile,baseline});assert.deepEqual(merged.runs.map(r=>r.id),['a','b','c']);assert.deepEqual(mergeDesktop(data,{runs:[],profile:data.profile,baseline}).runs.map(r=>r.id),['b']);});
test('desktop sync rejects same-record conflicts and deduplicates first connection',()=>{const data=defaultData(),a=runInput({id:'a',date:'2026-09-01',distance:5,movingSeconds:1800},'2026-09-06');data.runs=[{...a,distance:6}];assert.throws(()=>mergeDesktop(data,{runs:[{...a,distance:7}],profile:data.profile,baseline:{runs:[a],profile:data.profile}}),/obou/);data.runs=[a];assert.equal(mergeDesktop(data,{runs:[{...a,id:'desktop-a'}],profile:data.profile}).runs.length,1);});
