'use client';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Footprints, CalendarDays, MessageCircle, Settings, Plus, RefreshCw } from 'lucide-react';
import { localTime, monday, DAYS, MODEL } from '@/lib/domain.mjs';
const pace=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.round(seconds)%60).padStart(2,'0')}`;
export default function Runner({name}:{name:string}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('today'),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[clock,setClock]=useState<Date|null>(null),[key,setKey]=useState(''),[consent,setConsent]=useState(false),[message,setMessage]=useState('');
 const current=useRef<any>(null),working=useRef(false),autoTried=useRef('');
 const apply=(d:any)=>{current.current=d;setData(d);};
 async function reload(){try{const r=await fetch('/api/state',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);apply(d);return d;}catch(e:any){setError(e.message||'Připojení se nezdařilo.');return null;}}
 async function mutate(action:string,extra:any={},success='Uloženo ✓'){
 if(working.current)throw Error('Počkej na dokončení předchozí akce.');working.current=true;setBusy(action);setError('');setNotice('');
 try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,revision:current.current?.revision,...extra}),signal:AbortSignal.timeout(65000)});const d:any=await r.json();if(!r.ok){await reload();throw Error(d.error||'Uložení se nezdařilo.');}apply(d);setNotice(success);return d;}
 catch(e:any){setError(e.name==='TimeoutError'?'Požadavek trval příliš dlouho. Obnov data a ověř výsledek.':e.message||'Bez připojení nelze uložit změny.');throw e;}finally{working.current=false;setBusy('');}}
 const act=(action:string,extra:any={},success?:string)=>void mutate(action,extra,success).catch(()=>{});
 useEffect(()=>{void reload();setClock(new Date());const tick=setInterval(()=>setClock(new Date()),10000);const sync=()=>{if(!working.current)void reload();};window.addEventListener('focus',sync);window.addEventListener('online',sync);const poll=setInterval(()=>{if(document.visibilityState==='visible')sync();},30000);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{clearInterval(tick);clearInterval(poll);window.removeEventListener('focus',sync);window.removeEventListener('online',sync);};},[]);
 const today=clock?localTime(data?.timeZone||'Europe/Prague',clock).date:'';
 useEffect(()=>{if(!data?.automatic||!data.configured||busy||!today||!data.runs.length)return;const signature=JSON.stringify([today,data.runs,data.profile]);if(autoTried.current===signature)return;autoTried.current=signature;act('autoPlan',{},'Plán je aktuální ✓');},[data,busy,today]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const controller=new AbortController();Promise.resolve(mc.registerTool({name:'veyvo_add_run',description:'Uloží skutečný běh do VEYVO a aktualizuje zobrazenou historii.',inputSchema:{type:'object',properties:{date:{type:'string'},distance:{type:'number'},movingSeconds:{type:'number'},effort:{type:'integer'},note:{type:'string'}},required:['date','distance','movingSeconds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const d=await mutate('run',{run:input});return {saved:true,runCount:d.runs.length};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 const plan=today?data?.plans[monday(today)]:null;
 const submitRun=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),parts=String(f.get('time')).split(':').map(Number);if(parts.length<2||parts.length>3||parts.slice(1).some(n=>!Number.isInteger(n)||n<0||n>59)){setError('Čas zadej jako 30:00 nebo 1:30:00.');return;}void mutate('run',{run:{date:f.get('date'),distance:Number(f.get('distance')),movingSeconds:parts.reduce((s,n)=>s*60+n,0),effort:f.get('effort'),note:f.get('note')}},'Běh uložen ✓').then(()=>{form.reset();setTab('today');}).catch(()=>{});};
 return <main className="workspace"><header><img src="/veyvo-icon.png" width="48" height="48" alt=""/><strong>VEYVO</strong><span>{clock?new Intl.DateTimeFormat('cs-CZ',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:data?.timeZone||'Europe/Prague'}).format(clock):'Tvůj běžecký coach'}</span></header>
 <div className="feedback" aria-live="polite">{busy&&<p> {busy==='connect'?'Ověřuji NVIDIA připojení… může to trvat až minutu.':busy==='chat'?'Coach přemýšlí…':busy.includes('Plan')||busy==='plan'?'AI připravuje plán…':'Ukládám…'}</p>}{notice&&<p className="success">{notice}</p>}{error&&<p role="alert" className="error">{error} <button onClick={()=>void reload()}>Obnovit data</button></p>}</div>
 {!data?<section className="panel"><h1>Tvoje běhy, kdekoliv.</h1><p>Načítám uložená data…</p><Button onClick={()=>void reload()}>Zkusit znovu</Button></section>:<Tabs value={tab} onValueChange={v=>setTab(String(v))}>
 <TabsList className="navigation"><TabsTrigger value="today"><Footprints/>Běhy</TabsTrigger><TabsTrigger value="plan"><CalendarDays/>Plán</TabsTrigger><TabsTrigger value="coach"><MessageCircle/>Coach</TabsTrigger><TabsTrigger value="settings"><Settings/>Nastavení</TabsTrigger></TabsList>
 <TabsContent value="today"><section className="today"><p className="eyebrow">TVŮJ DALŠÍ KROK</p><h1>{plan?'Dnes podle tebe.':'Každý běh se počítá.'}</h1><p>{plan?.days[plan.dates.indexOf(today)]?.description||'Zapiš svůj poslední běh. Coach podle něj pozná tvoje tempo a připraví další trénink.'}</p><Button onClick={()=>document.getElementById('run-form')?.scrollIntoView({behavior:'smooth'})}><Plus/>Přidat běh</Button></section>
 <section className="metrics"><div><strong>{data.runs.filter((r:any)=>r.date>=new Date(Date.parse(today+'T12:00:00Z')-6*86400000).toISOString().slice(0,10)).reduce((s:number,r:any)=>s+r.distance,0).toFixed(1)}</strong><span>km za 7 dnů</span></div><div><strong>{data.runs.length}</strong><span>uložených běhů</span></div></section>
 <form id="run-form" className="panel form" onSubmit={submitRun}><h2>Přidat běh</h2><div className="columns"><label>Datum<Input name="date" type="date" required max={today} defaultValue={today}/></label><label>Vzdálenost (km)<Input name="distance" type="number" inputMode="decimal" min="0.01" max="300" step="0.01" required placeholder="5"/></label><label>Čas běhu<Input name="time" required placeholder="30:00" pattern="[0-9]{1,3}:[0-9]{2}(:[0-9]{2})?"/></label><label>Náročnost 1–10 (volitelné)<Input name="effort" type="number" min="1" max="10" inputMode="numeric" placeholder="Bez záznamu"/></label></div><label>Jak ses cítil?<Textarea name="note" maxLength={1000} placeholder="Pocity, terén, únava…"/></label><Button disabled={!!busy} type="submit">Uložit běh</Button></form>
 <section className="panel"><h2>Historie běhů</h2>{!data.runs.length&&<p>Zatím žádný běh. Záznamy z počítače můžeš importovat v Nastavení.</p>}{[...data.runs].sort((a:any,b:any)=>b.date.localeCompare(a.date)).map((r:any)=><article className="run" key={r.id}><div><strong>{r.distance} km</strong><p>{r.date} · {pace(r.movingSeconds)} · {pace(r.movingSeconds/r.distance)}/km{r.effort?` · náročnost ${r.effort}/10`:''}</p>{r.note&&<p>{r.note}</p>}</div><Button variant="ghost" disabled={!!busy} onClick={()=>act('deleteRun',{id:r.id},'Běh odstraněn')}>Smazat</Button></article>)}</section></TabsContent>
 <TabsContent value="plan"><section className="panel"><p className="eyebrow">PODLE TVÝCH VÝKONŮ</p><h1>Tvůj týdenní plán</h1><p>AI používá skutečné tempo, objem a náročnost posledních běhů. Dokončené běhy najdeš v historii.</p><Button disabled={!!busy||!data.configured} onClick={()=>act('plan',{},'Plán uložen ✓')}><RefreshCw/>Vytvořit / upravit plán</Button>{!data.configured&&<p>Nejdřív připoj NVIDIA v Nastavení.</p>}</section>{plan?<><p>{plan.explanation}</p>{plan.days.map((d:any,i:number)=><article key={i} className={'day '+(plan.dates[i]===today?'current':'')}><div><span>{DAYS[i]} · {plan.dates[i]}</span><h2>{d.type}</h2><p>{d.description}</p></div><strong>{d.distanceKm?`${d.distanceKm} km`: 'Volno'}{d.distanceKm>0&&<small>{pace(d.paceFast)}–{pace(d.paceSlow)}/km</small>}</strong></article>)}<p className="muted">Vytvořeno {new Date(plan.createdAt).toLocaleString('cs-CZ')} · NVIDIA Nemotron</p></>:<p>Pro tento týden zatím nemáš plán. Přidej aktuální běh a nech AI připravit další dny.</p>}</TabsContent>
 <TabsContent value="coach"><section className="panel"><p className="eyebrow">NVIDIA NEMOTRON</p><h1>VEYVO coach</h1><p>Prober své běhy, cíle nebo regeneraci. Plán upravíš tlačítkem v záložce Plán.</p></section><div className="messages" aria-live="polite">{data.chat.map((m:any,i:number)=><article key={i} className={'message '+m.role}><strong>{m.role==='user'?'Ty':'VEYVO'}</strong><p>{m.content}</p></article>)}</div><form className="form" onSubmit={e=>{e.preventDefault();void mutate('chat',{message},'Odpověď uložena ✓').then(()=>setMessage('')).catch(()=>{});}}><label>Zpráva coachovi<Textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={6000} required placeholder="Jak mám běžet po dnešním náročném tréninku?"/></label><Button type="submit" disabled={!!busy||!data.configured}>Odeslat</Button>{!data.configured&&<p>Připoj NVIDIA v Nastavení.</p>}</form></TabsContent>
 <TabsContent value="settings"><section className="panel"><h1>Nastavení</h1><p>{name} · data sdílená mezi telefonem a webem na počítači</p><a href="/signout-with-chatgpt?return_to=/" target="_top">Odhlásit se</a></section>
 <form className="panel form" onSubmit={e=>{e.preventDefault();void mutate('connect',{key,consent},'NVIDIA připojeno a klíč uložen ✓').then(()=>setKey('')).catch(()=>{});}}><h2>NVIDIA AI</h2><p className={data.configured?'success':'muted'}>{data.configured?'Připojeno ✓':'Zatím nepřipojeno'}</p><p><a href="https://build.nvidia.com/nvidia/nemotron-3.5-lightning-30b-a3b" target="_blank" rel="noreferrer">Získat NVIDIA API klíč</a> → přihlas se a zvol Generate API Key. Zkopíruj celý klíč; později bude skrytý.</p><label>API klíč<Input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="nvapi-…" required/></label><label>Model<Input value={MODEL} readOnly/></label><label className="check"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/>Souhlasím s odesíláním běžecké historie, poznámek, cíle, plánu a zpráv do NVIDIA pro odpovědi AI.</label><p className="muted">NVIDIA nabízí testovací API s limity. Dostupnost a podmínky určuje NVIDIA; trvale bezplatný provoz není zaručený. Klíč se ukládá na serveru šifrovaně.</p><Button disabled={!!busy} type="submit">{busy==='connect'?'Ověřuji…':'Uložit a ověřit připojení'}</Button>{data.configured&&<Button disabled={!!busy} variant="secondary" type="button" onClick={()=>act('disconnect',{},'NVIDIA odpojeno')}>Odpojit NVIDIA</Button>}</form>
 <form key={JSON.stringify(data.profile)+data.timeZone+data.automatic} className="panel form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),target=String(f.get('target')||'');const parts=target.split(':').map(Number);if(target&&(!/^\d{1,3}:\d{2}(:\d{2})?$/.test(target)||parts.slice(1).some(n=>n>59))){setError('Cílový čas zadej například 25:00.');return;}act('profile',{profile:{goalDistanceKm:Number(f.get('goal')),targetSeconds:target?parts.reduce((s,n)=>s*60+n,0):null,days:f.getAll('days').map(Number)},timeZone:f.get('zone'),automatic:f.get('automatic')==='on'});}}><h2>Běžecký profil</h2><div className="columns"><label>Cíl (km)<Input name="goal" type="number" min="1" max="100" step="0.1" defaultValue={data.profile.goalDistanceKm} required/></label><label>Cílový čas (volitelný)<Input name="target" placeholder="25:00" defaultValue={data.profile.targetSeconds?pace(data.profile.targetSeconds):''}/></label></div><fieldset><legend>Dny, kdy můžeš běhat (1–6)</legend><div className="days">{DAYS.map((d,i)=><label className="check" key={d}><Checkbox name="days" value={String(i)} defaultChecked={data.profile.days.includes(i)}/>{d}</label>)}</div></fieldset><label>Časové pásmo<Input name="zone" defaultValue={data.timeZone} required/></label><label className="check"><Checkbox name="automatic" defaultChecked={data.automatic}/>Automaticky upravovat plán po běhu a změně dne při otevřené aplikaci.</label><Button type="submit" disabled={!!busy}>Uložit profil</Button></form>
 <section className="panel form"><h2>Přenést běhy z počítače</h2><p>Ve Windows VEYVO vyexportuj data a zde vyber JSON soubor. Shodné běhy se nezdvojí. Původní Windows aplikace má vlastní lokální data; pro průběžnou synchronizaci používej tento web i na počítači.</p><label>Importovat export VEYVO<Input type="file" accept=".json,application/json" disabled={!!busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>800000)throw Error('Soubor je příliš velký.');const value=JSON.parse(await file.text());await mutate('import',{data:value},'Běhy importovány ✓');}catch(e:any){setError(e.message||'Import selhal.');}}}/></label><Button variant="secondary" onClick={()=>{const blob=new Blob([JSON.stringify({runs:data.runs,profile:data.profile},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='veyvo-behy.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Exportovat běhy</Button></section><section className="panel"><h2>VEYVO na iPhonu</h2><p>Otevři tento web v Safari. Klepni na Sdílet → Přidat na plochu. Na telefonu i počítači se přihlas stejným ChatGPT účtem. K synchronizaci a coachovi potřebuješ internet.</p></section></TabsContent>
 </Tabs> }</main>;
}
